# Generated by Django 5.0.1 on 2024-02-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_store_status_delete_data_remove_store_tz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store_status',
            name='store_id',
            field=models.IntegerField(),
        ),
    ]
