# Generated by Django 5.0.1 on 2024-02-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_store_store_id_alter_store_status_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='store_status',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store_status',
            name='store_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='store_tz',
            name='store_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
